### ISSUE TITLE
Is it possible to do "Destination charges"?

### ISSUE THREAD

**Issue by stef686** [ExpDev07/laravel-cashier-stripe-connect#14]
Does this package provide features to do "Destination charges" ie when a purchase is made the payment is split into fees to my platform, the remaining payment to the seller(s)? Or is this something that Cashier's functionality provides?

**Comment by ExpDev07** [comment]
You can do this through Cashier. This package is focused solely on adding the Connect features.

**Comment by ExpDev07** [comment]
Hello, you can achieve this through Cashier.

$userMakingPayment = ;
$userReceivingPayment = ;

$userMakingPayment ->charge(100, $paymentMethod, [
    'application_fee_amount => '123',
    'transfer_data[destination]' => $userReceivingPayment->stripeAccountId(),
]);
