### ISSUE TITLE
Call to undefined method Laravel\Cashier\Cashier::stripeOptions()

### ISSUE THREAD

**Issue by tdrabikdev** [ExpDev07/laravel-cashier-stripe-connect#16]
Hello guys, i just tried to use this package.

And i am getting this error.

`Call to undefined method Laravel\Cashier\Cashier::stripeOptions()`

This package will allow to make subscriptions in multi vendors ?

**Comment by ExpDev07** [comment]
You need to install Cashier also.

**Comment by tdrabikdev** [comment]
Not an cashier undefined method not class

**Comment by oleg-kolzhanov** [comment]
Same error.

In Laravel\Cashier no more method stripeOptions sinse v. 13:
https://github.com/laravel/cashier-stripe/blob/13.x/src/Cashier.php

**Comment by oleg-kolzhanov** [comment]
Fix is in main branch, but not in release.

**Comment by oleg-kolzhanov** [comment]
Main has error, create #17.

**Comment by ExpDev07** [comment]
Solved in https://github.com/ExpDev07/laravel-cashier-stripe-connect/pull/17.
