### ISSUE TITLE
Cashier Webhook

### ISSUE THREAD

**Issue by c-fitzmaurice** [ExpDev07/laravel-cashier-stripe-connect#2]
Hey there! This package looks awesome and is just what I need for an upcoming project...so thank you!

Just two questions...

1. Do you know if the Cashier webhook controller can handle Stripe Connect requests or would I have to implement my own?
2. In what scenario would you want to delete a User's Connect account and remake it using `deleteAndCreateStripeAccount`? Wouldn't this delete any validation and bank account steps a user has completed?

**Comment by ExpDev07** [comment]
1. I am not sure about this. Making your own should not be a hassle though.
2. The use case for this is if you want to restart the onboarding process. It would mean the user would have to re-enter their details yes.

**Comment by c-fitzmaurice** [comment]
Got it, thanks.

Would you be open to a PR to retrieve a Connect account's balance? It's the only thing missing that I would need and feel like it could be useful for anyone else.

Something like:

```
use Stripe\Balance;

public function retrieveConnectBalance(): Balance
{
    return Balance::([], [
            'stripe_account' => $this->stripeAccountId(),
        ]);
}
```

**Comment by c-fitzmaurice** [comment]
I went ahead and made the PR: https://github.com/ExpDev07/laravel-cashier-stripe-connect/pull/3

Looking forward to your thoughts!

**Comment by ExpDev07** [comment]
Absolutely. thanks for contributing! @c-fitzmaurice
