### ISSUE TITLE
Standard connect vs express & handling cuts

### ISSUE THREAD

**Issue by CitizenBeta** [ExpDev07/laravel-cashier-stripe-connect#5]
Hi! This package looks amazing, and I just have two questions:

1. Is there (or could there be) documentation for creating regular connect accounts vs express accounts?
2. What is the recommended way to take out your cut from the subscriptions you're setting up on behalf of connected accounts?

**Comment by ExpDev07** [comment]
1. Hey! Yeah, sorry for the bad docs. The `createAsStripeAccount` takes a type argument. Essentially you would do `$model->createAsStripeAccount('standard')` to create a standard Stripe Connect account for the model (user). The same goes for `createOrGetStripeAccount `and `deleteAndCreateStripeAccount`, they all take type as param with Express as default.
2. I believe this is done automatically through your Stripe dashboard. When you setup Connect, you can set what percentage you want.

**Comment by hbakouane** [comment]
Solved in #9
